name: Create Robopipe OS release

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-bookworm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build OS
        env:
          INSTALL_DEPS: true
        run: |
          ./build-os.sh

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ secrets.GITHUB_TOKEN }}
          release_name: Robopipe OS ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          assets_path: archive.swu
          asset_name: archive.swu
          asset_content_type: application/x-cpio
